logger:
  file: /tmp/open5gs-pwsiws.log

pwsiws:
  sbi:
    server:
      - address: 127.0.0.199
        port: 7778
    client:
      amf:
        - uri: http://127.0.0.5:7777
  sbcap:
    server:
      - address: 127.0.0.199  # PWS-IWS SBCAP server address
        port: 29168           # PWS-IWS SBCAP server port 